parameters:
#    tetram_test.example.class: Tetram\TestBundle\Example

services:
#    tetram_test.example:
#        class: %tetram_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
